export const routes = {
	HOME: '/',
	DASHBOARD: '/dashboard',
	LOGIN: '/login',
	REGISTER: '/register',
	MEDICINES: '/medicines',
	PURCHASE_REQUESTS: '/purchase-requests',
	PATIENTS: '/patients',
	PRESCRIPTIONS: '/prescriptions',
	RECORDS: {
		REGULAR: '/regular-records',
		PRENATAL: '/prenatal-records',
		IMMUNIZATION: '/immunization-records',
		ARCHIVED: '/archived-records',
	},
	SETTINGS: '/settings',
	USERS: '/users',
	PROFILE: '/profile',
	INVENTORIES: '/inventories',
	ILLNESS_HISTORIES: '/illness-histories',
	CHILD_VACCINATIONS: '/child-vaccinations',
	BABIES: '/babies',
};
